# Generated by Django 3.2.5 on 2022-06-13 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=70)),
                ('lastname', models.CharField(max_length=70)),
                ('email', models.CharField(max_length=90, unique=True)),
                ('phn', models.CharField(max_length=90, unique=True)),
                ('plan', models.CharField(max_length=70)),
            ],
        ),
    ]
